# Forward Sorted Data Code

## Step 1: Load and Read Data

In [31]:
import pandas as pd

In [32]:
df = pd.read_csv(r'/Users/mukikrishnan/Desktop/Interactive Soccer Dashboard/Positional Stats/Attacking/Raw Data/FBRef Top 5 Leagues Forward Statistics 23-24 With Positions - Sheet1.csv')

In [33]:
df

,Player,Pos,Season,Age,Nation,Team,Comp,MP,Min,90s,...,Live.1,Dead,FK.1,Sw,Crs,TI,CK,Head Won,Head Lost,Head Won%
0,Keyliane Abdallah,RW,2023-2024,17.0,fr FRA,Marseille,fr Ligue 1,1,4,0.0,...,1,0,0,0,0,0,0,0,1,0.0
1,Matthis Abline,ST,2023-2024,20.0,fr FRA,2 Teams,fr Ligue 1,22,1044,11.6,...,218,12,0,1,7,1,0,15,27,35.7
2,Zakaria Aboukhlal,RW,2023-2024,23.0,ma MAR,Toulouse,fr Ligue 1,13,754,8.4,...,185,11,1,0,5,9,0,6,7,46.2
3,Tammy Abraham,ST,2023-2024,25.0,eng ENG,Roma,it Serie A,8,242,2.7,...,37,2,0,0,2,0,0,6,5,54.5
4,BÃ©nie Adama Traore,LW,2023-2024,20.0,ci CIV,2 Teams,2 Comps,22,891,9.9,...,194,23,3,0,23,2,6,3,29,9.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
659,Anass Zaroury,LW,2023-2024,22.0,ma MAR,Burnley,eng Premier League,6,152,1.7,...,0,0,0,0,0,0,65,0,0,0.0
660,Edon Zhegrova,RW,2023-2024,24.0,xk KVX,Lille,fr Ligue 1,33,2288,25.4,...,6,6,12,0,0,0,905,6,6,12.0
661,Joshua Zirkzee,ST,2023-2024,22.0,nl NED,Bologna,it Serie A,34,2759,30.7,...,11,4,15,2,2,0,850,11,4,15.0
662,Simon Zoller,ST,2023-2024,32.0,de GER,Bochum,de Bundesliga,1,45,0.5,...,0,0,0,0,0,0,6,0,0,0.0
663,Lovro Zvonarek,SS,2023-2024,18.0,hr CRO,Bayern Munich,de Bundesliga,5,163,1.8,...,1,0,1,0,0,0,59,1,0,1.0

## Mapping Nations and Competitions

### Nations

In [34]:
unique_nations = df['Nation'].unique()

In [35]:
unique_nations

array(['fr FRA', 'ma MAR', 'eng ENG', 'ci CIV', 'ng NGA', 'at AUT',
       'am ARM', 'de GER', 'cr CRC', 'pt POR', 'py PAR', 'se SWE',
       'sn SEN', 'ch SUI', 'br BRA', 'rs SRB', 'jm JAM', 'gh GHA',
       'es ESP', 'uy URU', 'is ISL', 'jp JPN', 'ga GAB', 'ar ARG',
       'ir IRN', 'cd COD', 'gn GUI', 'us USA', 'zm ZAM', 'bf BFA',
       'tg TOG', 'sr SUR', 'it ITA', 'dz ALG', 'gw GNB', 'ml MLI',
       'nl NED', 'no NOR', 'gm GAM', 'co COL', 'hr CRO', 'cl CHI',
       'al ALB', 'wls WAL', 'sct SCO', 'ro ROU', 'be BEL', 'ie IRL',
       'cz CZE', 'dk DEN', 'ca CAN', 'mq MTQ', 'ba BIH', 'gr GRE',
       'ua UKR', 'mk MKD', 'za RSA', 'cm CMR', 'tr TUR', 'kr KOR',
       'mx MEX', 'zw ZIM', 'sl SLE', 'pl POL', 'tn TUN', 'me MNE',
       'ge GEO', 'pe PER', 'ao ANG', 'do DOM', 'eg EGY', 'bj BEN',
       'xk KVX', 'si SVN', 'uz UZB', 'il ISR', 'jo JOR', 'nz NZL'],
      dtype=object)

In [36]:
# Dictionary for renaming
rename_dict = {
    'fr FRA': 'France',
    'ma MAR': 'Morocco',
    'eng ENG': 'England',
    'ci CIV': 'Ivory Coast',
    'ng NGA': 'Nigeria',
    'at AUT': 'Austria',
    'am ARM': 'Armenia',
    'de GER': 'Germany',
    'cr CRC': 'Costa Rica',
    'pt POR': 'Portugal',
    'py PAR': 'Paraguay',
    'se SWE': 'Sweden',
    'sn SEN': 'Senegal',
    'ch SUI': 'Switzerland',
    'br BRA': 'Brazil',
    'rs SRB': 'Serbia',
    'jm JAM': 'Jamaica',
    'gh GHA': 'Ghana',
    'es ESP': 'Spain',
    'uy URU': 'Uruguay',
    'is ISL': 'Iceland',
    'jp JPN': 'Japan',
    'dk DEN': 'Denmark',
    'ga GAB': 'Gabon',
    'ar ARG': 'Argentina',
    'ir IRN': 'Iran',
    'cd COD': 'Democratic Republic of Congo',
    'gn GUI': 'Guinea',
    'us USA': 'United States',
    'zm ZAM': 'Zambia',
    'bf BFA': 'Burkina Faso',
    'tg TOG': 'Togo',
    'sr SUR': 'Suriname',
    'it ITA': 'Italy',
    'dz ALG': 'Algeria',
    'al ALB': 'Albania',
    'gw GNB': 'Guinea-Bissau',
    'ml MLI': 'Mali',
    'nl NED': 'Netherlands',
    'no NOR': 'Norway',
    'gm GAM': 'Gambia',
    'co COL': 'Colombia',
    'hr CRO': 'Croatia',
    'cl CHI': 'Chile',
    'wls WAL': 'Wales',
    'sct SCO': 'Scotland',
    'ro ROU': 'Romania',
    'be BEL': 'Belgium',
    'ie IRL': 'Ireland',
    'cz CZE': 'Czech Republic',
    'ca CAN': 'Canada',
    'mq MTQ': 'Martinique',
    'ba BIH': 'Bosnia and Herzegovina',
    'gr GRE': 'Greece',
    'ua UKR': 'Ukraine',
    'mk MKD': 'North Macedonia',
    'cm CMR': 'Cameroon',
    'za RSA': 'South Africa',
    'tr TUR': 'Turkey',
    'kr KOR': 'South Korea',
    'mx MEX': 'Mexico',
    'zw ZIM': 'Zimbabwe',
    'sl SLE': 'Sierra Leone',
    'pl POL': 'Poland',
    'tn TUN': 'Tunisia',
    'me MNE': 'Montenegro',
    'ge GEO': 'Georgia',
    'pe PER': 'Peru',
    'ao ANG': 'Angola',
    'km COM': 'Comoros',
    'do DOM': 'Dominican Republic',
    'eg EGY': 'Egypt',
    'bj BEN': 'Benin',
    'xk KVX': 'Kosovo',
    'si SVN': 'Slovenia',
    'uz UZB': 'Uzbekistan',
    'il ISR': 'Israel',
    'jo JOR': 'Jordan',
    'nz NZL': 'New Zealand'
}

In [37]:
# Replacing the values in the 'Nation' column
df['Nation'] = df['Nation'].replace()

/var/folders/57/9_8dmxg13rj6fbwyfxx4l3dr0000gn/T/ipykernel_82256/605981623.py:2: FutureWarning: Series.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  df['Nation'] = df['Nation'].replace()

In [38]:
# Replacing the values in the 'Nation' column
df['Nation'] = df['Nation'].replace(rename_dict)

In [39]:
print(df)

                 Player Pos     Season   Age       Nation           Team  \
0     Keyliane Abdallah  RW  2023-2024  17.0       France      Marseille
1        Matthis Abline  ST  2023-2024  20.0       France        2 Teams
2     Zakaria Aboukhlal  RW  2023-2024  23.0      Morocco       Toulouse
3         Tammy Abraham  ST  2023-2024  25.0      England           Roma
4    BÃ©nie Adama Traore  LW  2023-2024  20.0  Ivory Coast        2 Teams
..                  ...  ..        ...   ...          ...            ...
659       Anass Zaroury  LW  2023-2024  22.0      Morocco        Burnley
660       Edon Zhegrova  RW  2023-2024  24.0       Kosovo          Lille
661      Joshua Zirkzee  ST  2023-2024  22.0  Netherlands        Bologna
662        Simon Zoller  ST  2023-2024  32.0      Germany         Bochum
663      Lovro Zvonarek  SS  2023-2024  18.0      Croatia  Bayern Munich

                   Comp  MP   Min   90s  ...  Live.1  Dead  FK.1  Sw  Crs  TI  \
0            fr Ligue 1   1     4   0.0  ...       1     0     0   0    0   0
1            fr Ligue 1  22  1044  11.6  ...     218    12     0   1    7   1
2            fr Ligue 1  13   754   8.4  ...     185    11     1   0    5   9
3            it Serie A   8   242   2.7  ...      37     2     0   0    2   0
4               2 Comps  22   891   9.9  ...     194    23     3   0   23   2
..                  ...  ..   ...   ...  ...     ...   ...   ...  ..  ...  ..
659  eng Premier League   6   152   1.7  ...       0     0     0   0    0   0
660          fr Ligue 1  33  2288  25.4  ...       6     6    12   0    0   0
661          it Serie A  34  2759  30.7  ...      11     4    15   2    2   0
662       de Bundesliga   1    45   0.5  ...       0     0     0   0    0   0
663       de Bundesliga   5   163   1.8  ...       1     0     1   0    0   0

      CK  Head Won  Head Lost  Head Won%
0      0         0          1        0.0
1      0        15         27       35.7
2      0         6          7       46.2
3      0         6          5       54.5
4      6         3         29        9.4
..   ...       ...        ...        ...
659   65         0          0        0.0
660  905         6          6       12.0
661  850        11          4       15.0
662    6         0          0        0.0
663   59         1          0        1.0

[664 rows x 69 columns]

### Competitions

In [40]:
unique_competitions = df['Comp'].unique()

In [41]:
unique_competitions

array(['fr Ligue 1', 'it Serie A', '2 Comps', 'de Bundesliga',
       'eng Premier League', 'es La Liga'], dtype=object)

In [42]:
# Dictionary for renaming
rename_comp_dict = {
    'eng Premier League': 'Premier League',
    'it Serie A': 'Serie A',
    'de Bundesliga': 'Bundesliga',
    'fr Ligue 1': 'Ligue 1',
    'es La Liga': 'La Liga',
}

In [43]:
# Replacing the values in the 'Nation' column
df['Comp'] = df['Comp'].replace(rename_comp_dict)

In [44]:
df

,Player,Pos,Season,Age,Nation,Team,Comp,MP,Min,90s,...,Live.1,Dead,FK.1,Sw,Crs,TI,CK,Head Won,Head Lost,Head Won%
0,Keyliane Abdallah,RW,2023-2024,17.0,France,Marseille,Ligue 1,1,4,0.0,...,1,0,0,0,0,0,0,0,1,0.0
1,Matthis Abline,ST,2023-2024,20.0,France,2 Teams,Ligue 1,22,1044,11.6,...,218,12,0,1,7,1,0,15,27,35.7
2,Zakaria Aboukhlal,RW,2023-2024,23.0,Morocco,Toulouse,Ligue 1,13,754,8.4,...,185,11,1,0,5,9,0,6,7,46.2
3,Tammy Abraham,ST,2023-2024,25.0,England,Roma,Serie A,8,242,2.7,...,37,2,0,0,2,0,0,6,5,54.5
4,BÃ©nie Adama Traore,LW,2023-2024,20.0,Ivory Coast,2 Teams,2 Comps,22,891,9.9,...,194,23,3,0,23,2,6,3,29,9.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
659,Anass Zaroury,LW,2023-2024,22.0,Morocco,Burnley,Premier League,6,152,1.7,...,0,0,0,0,0,0,65,0,0,0.0
660,Edon Zhegrova,RW,2023-2024,24.0,Kosovo,Lille,Ligue 1,33,2288,25.4,...,6,6,12,0,0,0,905,6,6,12.0
661,Joshua Zirkzee,ST,2023-2024,22.0,Netherlands,Bologna,Serie A,34,2759,30.7,...,11,4,15,2,2,0,850,11,4,15.0
662,Simon Zoller,ST,2023-2024,32.0,Germany,Bochum,Bundesliga,1,45,0.5,...,0,0,0,0,0,0,6,0,0,0.0
663,Lovro Zvonarek,SS,2023-2024,18.0,Croatia,Bayern Munich,Bundesliga,5,163,1.8,...,1,0,1,0,0,0,59,1,0,1.0

### Export Clean Data

In [45]:
df.to_csv(r'/Users/mukikrishnan/Desktop/Interactive Soccer Dashboard/Positional Stats/Attacking/Sorted Data/ForwardsSortedData.csv')